ChivoFlixWeb/Models/Facturaciones.cs
using System;
using System.Collections.Generic;

#nullable disable

namespace ChivoFlixWeb.Models
{
    public partial class Facturaciones
    {
        public int IdFacturaciones { get; set; }
        public int IdUsuarios { get; set; }
        public int IdPlanes { get; set; }
        public string Plann { get; set; }
        public DateTime? FechaAdquirido { get; set; }
        public string Tipo { get; set; }
        public double Precio { get; set; }
        public double Total { get; set; }

        public virtual Planes IdPlanesNavigation { get; set; }
        public virtual Usuarios IdUsuariosNavigation { get; set; }
    }
}

ChivoFlixWeb/Controllers/FacturacionesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ChivoFlixWeb.Models;
using Rotativa.AspNetCore;
using Microsoft.EntityFrameworkCore.Query;

namespace ChivoFlixWeb.Controllers
{
    public class FacturacionesController : Controller
    {
        private readonly CHIVOFLIXContext _context;

        public FacturacionesController(CHIVOFLIXContext context)
        {
            _context = context;
        }

        // GET: Facturaciones
        public async Task<IActionResult> Index()
        {
            IIncludableQueryable<Facturaciones, Usuarios> cHIVOFLIXContext = GetFacturaciones();
            return View(await cHIVOFLIXContext.ToListAsync());
        }

        private IIncludableQueryable<Facturaciones, Usuarios> GetFacturaciones()
        {
            return _context.Facturaciones.Include(f => f.IdPlanesNavigation).Include(f => f.IdUsuariosNavigation);
        }

        // GET: Facturaciones/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var facturaciones = await _context.Facturaciones
                .Include(f => f.IdPlanesNavigation)
                .Include(f => f.IdUsuariosNavigation)
                .FirstOrDefaultAsync(m => m.IdFacturaciones == id);
            if (facturaciones == null)
            {
                return NotFound();
            }

            return View(facturaciones);
        }

        // GET: Facturaciones/Create
        public IActionResult Create()
        {
            ViewData["IdPlanes"] = new SelectList(_context.Planes, "IdPlanes", "Plann");
            ViewData["IdUsuarios"] = new SelectList(_context.Usuarios, "IdUsuarios", "Email");
            return View();
        }

        // POST: Facturaciones/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdFacturaciones,IdUsuarios,IdPlanes,Plann,FechaAdquirido,Tipo,Precio,Total")] Facturaciones facturaciones)
        {
            if (ModelState.IsValid)
            {
                _context.Add(facturaciones);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdPlanes"] = new SelectList(_context.Planes, "IdPlanes", "Plann", facturaciones.IdPlanes);
            ViewData["IdUsuarios"] = new SelectList(_context.Usuarios, "IdUsuarios", "Email", facturaciones.IdUsuarios);
            return View(facturaciones);
        }

        // GET: Facturaciones/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var facturaciones = await _context.Facturaciones.FindAsync(id);
            if (facturaciones == null)
            {
                return NotFound();
            }
            ViewData["IdPlanes"] = new SelectList(_context.Planes, "IdPlanes", "Plann", facturaciones.IdPlanes);
            ViewData["IdUsuarios"] = new SelectList(_context.Usuarios, "IdUsuarios", "Email", facturaciones.IdUsuarios);
            return View(facturaciones);
        }

        // POST: Facturaciones/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdFacturaciones,IdUsuarios,IdPlanes,Plann,FechaAdquirido,Tipo,Precio,Total")] Facturaciones facturaciones)
        {
            if (id != facturaciones.IdFacturaciones)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(facturaciones);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FacturacionesExists(facturaciones.IdFacturaciones))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdPlanes"] = new SelectList(_context.Planes, "IdPlanes", "Plann", facturaciones.IdPlanes);
            ViewData["IdUsuarios"] = new SelectList(_context.Usuarios, "IdUsuarios", "Email", facturaciones.IdUsuarios);
            return View(facturaciones);
        }

        // GET: Facturaciones/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var facturaciones = await _context.Facturaciones
                .Include(f => f.IdPlanesNavigation)
                .Include(f => f.IdUsuariosNavigation)
                .FirstOrDefaultAsync(m => m.IdFacturaciones == id);
            if (facturaciones == null)
            {
                return NotFound();
            }

            return View(facturaciones);
        }

        // POST: Facturaciones/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var facturaciones = await _context.Facturaciones.FindAsync(id);
            _context.Facturaciones.Remove(facturaciones);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FacturacionesExists(int id)
        {
            return _context.Facturaciones.Any(e => e.IdFacturaciones == id);
        }

        public IActionResult Reporte()
        {
            return new ViewAsPdf("Reporte", GetFacturaciones().ToList())
            {

            };
        }
    }
}

ChivoFlixWeb/Views/Facturaciones/Details.cshtml
@model ChivoFlixWeb.Models.Facturaciones

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Facturaciones</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Plann)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Plann)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaAdquirido)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaAdquirido)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Tipo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Tipo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Precio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Precio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Total)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Total)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdPlanesNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdPlanesNavigation.Plann)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdUsuariosNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdUsuariosNavigation.Email)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.IdFacturaciones">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

ChivoFlixWeb/Views/Facturaciones/Index.cshtml
@model IEnumerable<ChivoFlixWeb.Models.Facturaciones>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Facturaciones</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Plann)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaAdquirido)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Tipo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Precio)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Total)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdUsuariosNavigation.Email)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Plann)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FechaAdquirido)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Tipo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Precio)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Total)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IdUsuariosNavigation.Email)
                </td>
            </tr>
        }
    </tbody>
</table>
<div class="row right">
    <a asp-controller="Facturaciones" asp-action="Reporte" class="btn btn-outline-dark inputBox col-md-2 card-text-center">Generar reporte</a>
</div>

ChivoFlixWeb/Views/Facturaciones/Reporte.cshtml
@model IEnumerable<ChivoFlixWeb.Models.Facturaciones>

@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <title>Reporte</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ChivoFlixWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">
</head>
<body>
    <div class="text-center">
        <table>
            <tbody>
                <tr>
                    <td colspan="4"><img src="~/img/chivoflix.png" style="height:90%" /></td>
                    <td colspan="2" class="text-right"><img src="~/img/logoutec.png" style="width:60%; height:30%" /></td>
                </tr>
            </tbody>
        </table>
        <hr />
        <div class="col-md-12">
            <h3 class="font-weight-bold">Reporte Peliculas</h3>
        </div>
        <hr />
        <div class="col-md-12">
            <table class="table">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Plann)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.FechaAdquirido)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Tipo)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Precio)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Total)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.IdUsuariosNavigation.Email)
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Plann)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.FechaAdquirido)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Tipo)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Precio)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Total)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.IdUsuariosNavigation.Email)
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</body>
</html>