ChivoFlixWeb/Controllers/PeliculasController.cs
using ChivoFlixWeb.Models;
using ChivoFlixWeb.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Rotativa.AspNetCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ChivoFlixWeb.Controllers
{
    public class PeliculasController : Controller
    {
        private readonly CHIVOFLIXContext _context;
        public PeliculasController(CHIVOFLIXContext context)
        {
            _context = context;
        }
        public IActionResult Listado()
        {
            List<Peliculas> listPeliculas;
            listPeliculas = GetPeliculas();
            return View(listPeliculas);
        }

        private List<Peliculas> GetPeliculas()
        {
            return (from pelicula in _context.Peliculas
                    select new Peliculas
                    {
                        IdPeliculas = pelicula.IdPeliculas,
                        Nombre = pelicula.Nombre,
                        AnioEstreno = pelicula.AnioEstreno,
                        CategoriaEdad = pelicula.CategoriaEdad,
                        Descripcion = pelicula.Descripcion,
                        Calidad = pelicula.Calidad,
                        Director = pelicula.Director,
                        Banner = pelicula.Banner,
                        IdGeneros = pelicula.IdGeneros,
                        Pelicula1 = pelicula.Pelicula1
                    }).ToList();
        }

        public IActionResult NuevaPelicula()
        {
            List<Generos> listadoGeneros = null;

            listadoGeneros = (from g in _context.Generos
                              select new Generos()
                              {
                                  IdGeneros = g.IdGeneros,
                                  Nombre = g.Nombre
                              }).ToList();

            List<SelectListItem> items = listadoGeneros.ConvertAll(g =>
           {
               return new SelectListItem()
               {
                   Text = g.Nombre.ToString(),
                   Value = g.IdGeneros.ToString(),
                   Selected = false,
               };
           });

            ViewBag.items = items;
            return View();
        }
        [HttpPost]
        public IActionResult NuevaPelicula(PeliculaVM model)
        {
            var db = _context;
            try
            {
                if (ModelState.IsValid)
                {
                    var oPeliculas = new Peliculas
                    {
                        Nombre = model.nombre,
                        AnioEstreno = model.anioEstreno,
                        CategoriaEdad = model.categoriaEdad,
                        Descripcion = model.descripcion,
                        Calidad = model.calidad,
                        Director = model.director,
                        Banner = model.banner,
                        IdGeneros = model.idGeneros,
                        Pelicula1 = model.Pelicula,
                    };
                    db.Peliculas.Add(oPeliculas);
                    db.SaveChanges();
                    TempData["notification"] = "<script language='javascript'>Swal.fire({icon: 'success',title: 'Hecho',text: 'Pelicula agregada correctamente!',})</script>";
                    return Redirect("~/Peliculas/Listado/");
                }
                return View(model);
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }

        public IActionResult EditarPelicula(int id)
        {

            List<Generos> listadoGeneros = null;

            listadoGeneros = (from g in _context.Generos
                              select new Generos()
                              {
                                  IdGeneros = g.IdGeneros,
                                  Nombre = g.Nombre
                              }).ToList();

            List<SelectListItem> items = listadoGeneros.ConvertAll(g =>
            {
                return new SelectListItem()
                {
                    Text = g.Nombre.ToString(),
                    Value = g.IdGeneros.ToString(),
                    Selected = false,
                };
            });

            ViewBag.items = items;

            PeliculaVM model = new();
            var peliculas = _context.Peliculas.Find(id);
            model.IdPeliculas = peliculas.IdPeliculas;
            model.nombre = peliculas.Nombre;
            model.descripcion = peliculas.Descripcion;
            model.anioEstreno = peliculas.AnioEstreno;
            model.categoriaEdad = peliculas.CategoriaEdad;
            model.calidad = peliculas.Calidad;
            model.director = peliculas.Director;
            model.banner = peliculas.Banner;
            model.idGeneros = peliculas.IdGeneros;
            model.Pelicula = peliculas.Pelicula1;

            return View(model);
        }

        [HttpPost]
        public IActionResult EditarPelicula(PeliculaVM model)
        {
            var db = _context;

            if (ModelState.IsValid)
            {
                var peliculas = db.Peliculas.Find(model.IdPeliculas);
                peliculas.Nombre = model.nombre;
                peliculas.AnioEstreno = model.anioEstreno;
                peliculas.CategoriaEdad = model.categoriaEdad;
                peliculas.Descripcion = model.descripcion;
                peliculas.Calidad = model.calidad;
                peliculas.Director = model.director;
                peliculas.Banner = model.banner;
                peliculas.IdGeneros = model.idGeneros;
                peliculas.Pelicula1 = model.Pelicula;

                db.Entry(peliculas).State = EntityState.Modified;
                db.SaveChanges();
                TempData["notification"] = "<script language='javascript'>Swal.fire({icon: 'success',title: 'Hecho',text: 'Pelicula Editada!',})</script>";
                return Redirect("~/Peliculas/Listado");
            }
            return View(model);

        }

        [HttpGet]
        public IActionResult EliminarPelicula(int id)
        {
            var db = _context;
            using (db)
            {
                var peliculas = db.Peliculas.Find(id);
                db.Peliculas.Remove(peliculas);
                db.SaveChanges();
            }
            TempData["notification"] = "<script language='javascript'>Swal.fire({icon: 'error',title: 'Hecho',text: 'Pelicula Eliminada!',})</script>";
            return Redirect("~/Peliculas/Listado");
        }
        public IActionResult Reporte()
        {
            return new ViewAsPdf("Reporte", GetPeliculas())
            {

            };
        }
    }
}

ChivoFlixWeb/Controllers/PlanesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ChivoFlixWeb.Models;

namespace ChivoFlixWeb.Controllers
{
    public class PlanesController : Controller
    {
        private readonly CHIVOFLIXContext _context;

        public PlanesController(CHIVOFLIXContext context)
        {
            _context = context;
        }

        // GET: Planes
        public async Task<IActionResult> Index()
        {
            var cHIVOFLIXContext = _context.Planes.Include(p => p.IdDuracionPlanesNavigation).Include(p => p.IdUsuariosNavigation);
            return View(await cHIVOFLIXContext.ToListAsync());
        }

        // GET: Planes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var planes = await _context.Planes
                .Include(p => p.IdDuracionPlanesNavigation)
                .Include(p => p.IdUsuariosNavigation)
                .FirstOrDefaultAsync(m => m.IdPlanes == id);
            if (planes == null)
            {
                return NotFound();
            }

            return View(planes);
        }

        // GET: Planes/Create
        public IActionResult Create()
        {
            ViewData["IdDuracionPlanes"] = new SelectList(_context.DuracionPlanes, "IdDuracionPlanes", "Nombre");
            ViewData["IdUsuarios"] = new SelectList(_context.Usuarios, "IdUsuarios", "Email");
            return View();
        }

        // POST: Planes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdPlanes,Plann,PrecioPlan,IdDuracionPlanes,IdUsuarios")] Planes planes)
        {
            if (ModelState.IsValid)
            {
                _context.Add(planes);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdDuracionPlanes"] = new SelectList(_context.DuracionPlanes, "IdDuracionPlanes", "Nombre", planes.IdDuracionPlanes);
            ViewData["IdUsuarios"] = new SelectList(_context.Usuarios, "IdUsuarios", "Email", planes.IdUsuarios);
            return View(planes);
        }

        // GET: Planes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var planes = await _context.Planes.FindAsync(id);
            if (planes == null)
            {
                return NotFound();
            }
            ViewData["IdDuracionPlanes"] = new SelectList(_context.DuracionPlanes, "IdDuracionPlanes", "Nombre", planes.IdDuracionPlanes);
            ViewData["IdUsuarios"] = new SelectList(_context.Usuarios, "IdUsuarios", "Email", planes.IdUsuarios);
            return View(planes);
        }

        // POST: Planes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdPlanes,Plann,PrecioPlan,IdDuracionPlanes,IdUsuarios")] Planes planes)
        {
            if (id != planes.IdPlanes)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(planes);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PlanesExists(planes.IdPlanes))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdDuracionPlanes"] = new SelectList(_context.DuracionPlanes, "IdDuracionPlanes", "Nombre", planes.IdDuracionPlanes);
            ViewData["IdUsuarios"] = new SelectList(_context.Usuarios, "IdUsuarios", "Email", planes.IdUsuarios);
            return View(planes);
        }

        // GET: Planes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var planes = await _context.Planes
                .Include(p => p.IdDuracionPlanesNavigation)
                .Include(p => p.IdUsuariosNavigation)
                .FirstOrDefaultAsync(m => m.IdPlanes == id);
            if (planes == null)
            {
                return NotFound();
            }

            return View(planes);
        }

        // POST: Planes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var planes = await _context.Planes.FindAsync(id);
            _context.Planes.Remove(planes);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PlanesExists(int id)
        {
            return _context.Planes.Any(e => e.IdPlanes == id);
        }
    }
}

ChivoFlixWeb/Controllers/UsuariosController.cs
using ChivoFlixWeb.Models;
using ChivoFlixWeb.Models.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Rotativa.AspNetCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ChivoFlixWeb.Controllers
{
    
    public class UsuariosController : Controller
    {
        private readonly CHIVOFLIXContext _contexto;

        public UsuariosController(CHIVOFLIXContext context)
        {
            _contexto = context;
        }
        public IActionResult Listado()
        {
            HttpContext.Session.GetString("String");

            List<Usuarios> listUsuarios = GetUsuarios();
            return View(listUsuarios);
        }

        private List<Usuarios> GetUsuarios()
        {
            return (from u in _contexto.Usuarios
                    select new Usuarios
                    {
                        IdUsuarios = u.IdUsuarios,
                        Username = u.Username,
                        Email = u.Email,
                        Password = u.Password,
                        Perfiles = u.Perfiles,
                        Imagen = u.Imagen,
                        IdPlanes = u.IdPlanes,
                        IdRol = u.IdRol,
                        IdPlanesNavigation = u.IdPlanesNavigation,
                        Planes = u.Planes,
                        IdRolNavigation = u.IdRolNavigation
                    }).Where(x => x.IdRol == 2).ToList();
        }

        public IActionResult NuevoUsuario()
        {
            return View();
        }

        [HttpPost]
        public IActionResult NuevoUsuario(UsuarioVM model)
        {
            var db = _contexto;
            try
            {
                if (ModelState.IsValid)
                {
                    var oUsuario = new Usuarios
                    {
                        Username = model.Username,
                        Email = model.Email,
                        Password = model.Password,
                        Imagen = model.Imagen,
                        IdRol = 1,
                        IdPlanes = 3,
                        Perfiles = 4,
                    };
                    db.Usuarios.Add(oUsuario);
                    db.SaveChanges();
                    return Redirect("~/Usuarios/Listado/");
                }
                return View(model);
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }

        public IActionResult EditarUsuario(int id)
        {
            UsuarioVM model = new();
            var oUsuario = _contexto.Usuarios.Find(id);
            model.IdUsuarios = oUsuario.IdUsuarios;
            model.Username = oUsuario.Username;
            model.Email = oUsuario.Email;
            model.Password = oUsuario.Password;
            model.Imagen = oUsuario.Imagen;

            return View(model);
        }

        [HttpPost]
        public IActionResult EditarUsuario(UsuarioVM model)
        {
            var db = _contexto;
            try
            {
                if (ModelState.IsValid)
                {
                    var oUsuario = db.Usuarios.Find(model.IdUsuarios);
                    oUsuario.Username = model.Username;
                    oUsuario.Email = model.Email;
                    oUsuario.Password = model.Password;
                    oUsuario.Imagen = model.Imagen;
                    oUsuario.IdRol = 1;
                    oUsuario.IdPlanes = 3;
                    oUsuario.Perfiles = 4;

                    db.Entry(oUsuario).State = EntityState.Modified;
                    db.SaveChanges();

                    return Redirect("~/Usuarios/Listado");
                }
                return View(model);
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }

        [HttpGet]
        public IActionResult EliminarUsuario(int id)
        {
            var db = _contexto;
            using (db)
            {
                var oUsuario = db.Usuarios.Find(id);
                db.Usuarios.Remove(oUsuario);
                db.SaveChanges();
            }
            return Redirect("~/Usuarios/Listado");
        }
        [HttpGet]
        public IActionResult VerUsuario(int id)
        {
            var db = _contexto;
            UsuarioVM model = new();
            using (db)
            {
                var oUsuario = db.Usuarios.Find(id);
                model.IdUsuarios = oUsuario.IdUsuarios;
                model.Username = oUsuario.Username;
                model.Email = oUsuario.Email;
                model.Password = oUsuario.Password;
                model.Imagen = oUsuario.Imagen;
            }
            return View(model);
        }

        public IActionResult Reporte()
        {
            return new ViewAsPdf("Reporte", GetUsuarios())
            {

            };
        }
    }
}

ChivoFlixWeb/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http;
@{
    if (Context.Session.GetString("username") == null)
    {
        Context.Response.Redirect("../Account/login");
    }
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ChivoFlixWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">
    <link rel="shortcut icon" href="~/img/c.png">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-dark">
        <div class="container">
            <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index">ChivoFlixWeb</a>
            <button class="navbar-toggler border-white bg-light" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav">
                    <li class="nav-item active">
                        <a class="nav-link text-white" asp-controller="Usuarios" asp-action="Listado">Usuarios</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Peliculas
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" asp-controller="Peliculas" asp-action="Listado">Listado de peliculas</a>
                            <a class="dropdown-item" asp-controller="Peliculas" asp-action="NuevaPelicula">Agregar pelicula</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Categorias
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" asp-controller="Categorias" asp-action="Listado">Listado de categorias</a>
                            <a class="dropdown-item" asp-controller="Categorias" asp-action="NuevaCategoria">Agregar categoria</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Planes
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" asp-controller="Planes" asp-action="Index">Planes</a>
                            <a class="dropdown-item" asp-controller="DuracionPlanes" asp-action="Index">Duracion de planes</a>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" asp-controller="Facturaciones" asp-action="Index">Facturacion</a>
                    </li>
                </ul>
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item d-none d-sm-inline-block">
                        <a class="nav-link text-uppercase text-white">@Context.Session.GetString("username")</a>
                    </li>
                    <li class="nav-item d-none d-sm-inline-block">
                        <a href="@Url.Action("Logout","Account")" class="nav-link text-white btn btn-outline-danger">Cerrar Sesion</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <br />

    <div class="container">
        <main role="main">
            @RenderBody()
        </main>
    </div>

    <br />

    <footer>
        <div class="card text-center">
            <div class="card-body">
                <h5 class="card-title">ChivoFlixWeb</h5>
                &copy; 2022 - ChivoFlixWeb - <a asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>