ChivoFlixWeb/Models/Listados.cs
using System;
using System.Collections.Generic;

#nullable disable

namespace ChivoFlixWeb.Models
{
    public partial class Listados
    {
        public int IdListado { get; set; }
        public int IdPeliculas { get; set; }
        public int IdUsuarios { get; set; }

        public virtual Peliculas IdPeliculasNavigation { get; set; }
        public virtual Usuarios IdUsuariosNavigation { get; set; }
    }
}

ChivoFlixWeb/Controllers/CategoriasController.cs
using ChivoFlixWeb.Models;
using ChivoFlixWeb.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ChivoFlixWeb.Controllers
{
    public class CategoriasController : Controller
    {
        private readonly CHIVOFLIXContext _context;
        public CategoriasController(CHIVOFLIXContext context)
        {
            _context = context;
        }
        public IActionResult Listado()
        {
            List<Generos> listGeneros;
            listGeneros = (from g in _context.Generos
                           select new Generos
                           {
                               IdGeneros = g.IdGeneros,
                               Nombre= g.Nombre
                           }).ToList();
            return View(listGeneros);
        }

        public IActionResult NuevaPelicula()
        {
            List<Generos> listadoGeneros = null;

            listadoGeneros = (from g in _context.Generos
                              select new Generos()
                              {
                                  IdGeneros = g.IdGeneros,
                                  Nombre = g.Nombre
                              }).ToList();

            List<SelectListItem> items = listadoGeneros.ConvertAll(g =>
            {
                return new SelectListItem()
                {
                    Text = g.Nombre.ToString(),
                    Value = g.IdGeneros.ToString(),
                    Selected = false,
                };
            });

            ViewBag.items = items;
            return View();
        }

        public IActionResult NuevaCategoria()
        {
            return View();
        }

        [HttpPost]
        public IActionResult NuevaCategoria(GenerosVM model)
        {
            var db = _context;
            try
            {
                if (ModelState.IsValid)
                {
                    var oGeneros = new Generos
                    {
                        IdGeneros = model.IdGeneros,
                        Nombre = model.Nombre
                       
                       
                    };
                    db.Generos.Add(oGeneros);
                    db.SaveChanges();
                    return Redirect("~/Categorias/Listado/");
                }
                return View(model);
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }


        public IActionResult EditarCategoria(int id)
        {
            GenerosVM model = new();
            var oGenero = _context.Generos.Find(id);
            model.IdGeneros = oGenero.IdGeneros;
            model.Nombre = oGenero.Nombre;
            

            return View(model);
        }

        [HttpPost]
        public IActionResult EditarCategoria(GenerosVM model)
        {
            var db = _context;
            try
            {
                if (ModelState.IsValid)
                {
                    var oGenero = db.Generos.Find(model.IdGeneros);
                    oGenero.Nombre = model.Nombre;
                   
                   

                    db.Entry(oGenero).State = EntityState.Modified;
                    db.SaveChanges();

                    return Redirect("~/Categorias/Listado");
                }
                return View(model);
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }

        [HttpGet]
        public IActionResult EliminarCategoria(int id)
        {
            var db = _context;
            using (db)
            {
                var genero = db.Generos.Find(id);
                db.Generos.Remove(genero);
                db.SaveChanges();
            }
            return Redirect("~/Categorias/Listado");
        }
    }
}

ChivoFlixWeb/Views/Categorias/EditarCategoria.cshtml
@model ChivoFlixWeb.Models.ViewModels.GenerosVM
@{
    ViewBag.Title = "Editar Categoria";
    List<SelectListItem> items = (List<SelectListItem>)ViewBag.items;
}

<h2>Editar Categoria</h2>

@using (Html.BeginForm("EditarCategoria", "Categorias", FormMethod.Post))
{
    <div class="row">
        <div class="col-md-12">
            <div>
                @Html.LabelFor(d => d.IdGeneros)
                @Html.TextBoxFor(d => d.IdGeneros, "", new { @class = "form-control", @readonly = "readonly" })
            </div>
            <div>
                @Html.LabelFor(d => d.Nombre)
                @Html.TextBoxFor(d => d.Nombre, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.Nombre, null, new { @class = "text-danger" })
            </div>
           
            <br />
            <div class="row">
                <div class="col-md-6">
                </div>
                <div class="col-md-6">
                    <input value="Guardar" class="btn btn-primary" type="submit" />

                    <a href="/Peliculas/Listado" class="btn btn-success">Regresar</a>
                </div>
            </div>
        </div>
    </div>
}

ChivoFlixWeb/Views/Categorias/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

ChivoFlixWeb/Views/Categorias/Listado.cshtml
@model List<ChivoFlixWeb.Models.Generos>
@{
    ViewBag.Title = "Categorias";
}

<h2>Listado de Categorias</h2>
<div class="row right">
    <a href="~/Categorias/NuevaCategoria" class="btn btn-primary col-md-2 card-text-center">Nueva Categoria</a>
</div>
<br />
<div class="row">
    <div class="col-md-12">
        <table class="table">
            <thead class="thead-dark">
                <tr>
                    <th>ID</th>
                    <th>Nombre</th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @if (Model.Any())
                {
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.IdGeneros</td>
                            <td>@item.Nombre</td>
                           
                            <td>
                                <a href="~/Categorias/EditarCategoria/@item.IdGeneros" class="btn btn-primary"><i class="bi bi-pencil-square"></i></a>
                            </td>
                            <td>
                                <a href="~/Categorias/EliminarCategoria/@item.IdGeneros" class="btn btn-danger"><i class="bi bi-trash"></i></a>
                            </td>
                        </tr>
                    }
                }
                else
                {
                    <tr>
                        <th scope="row">No hay registros</th>
                    </tr>
                }
            </tbody>

        </table>
    </div>
</div>

ChivoFlixWeb/Views/Categorias/NuevaCategoria.cshtml
@model ChivoFlixWeb.Models.ViewModels.GenerosVM
@{
    ViewBag.Title = "NuevaCategoria";
    List<SelectListItem> items = (List<SelectListItem>)ViewBag.items;
}

<h2>Nueva Categoria</h2>

@using (Html.BeginForm("NuevaCategoria","Categorias",FormMethod.Post))
{
    <div class="row">
        <div class="col-md-12">
            <div>
                @Html.LabelFor(d => d.Nombre)
                @Html.TextBoxFor(d => d.Nombre, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.Nombre, null, new { @class = "text-danger" })
            </div>
            
            <br />
            <div>
                <input value="Guardar" class="btn btn-primary" type="submit" />
            </div>
        </div>
    </div>
}